apiVersion: apps/v1
kind: Deployment
metadata:
  name: year7angularapp
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: ashishmrm/year7angularapp:latest
          ports:
            - containerPort: 80
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: year7angularapp
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
